version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 14 # Note: Unless dependencies are pinned/locked, the effect is limited.
    commit-message:
      prefix: ''
    labels: []
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    cooldown:
      default-days: 14
    commit-message:
      prefix: ''
    labels: []
