only_if: $CIRRUS_TAG == '' && ($CIRRUS_PR != '' || $CIRRUS_BRANCH == 'master')
auto_cancellation: $CIRRUS_PR != ''
env:
  CARGO_INCREMENTAL: '0'
  CARGO_NET_RETRY: '10'
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: '1'
  RUSTDOCFLAGS: -D warnings
  RUSTFLAGS: -D warnings
  RUSTUP_MAX_RETRIES: '10'

aarch64_linux_task:
  name: test ($TARGET)
  env:
    TARGET: aarch64-unknown-linux-gnu
  arm_container:
    image: rust
  setup_script:
    - rustup toolchain add nightly && rustup default nightly
  test_script:
    - cargo test --all --all-features --exclude benchmarks -- --test-threads=1
    - cargo test --all --all-features --exclude benchmarks --release -- --test-threads=1

aarch64_macos_task:
  name: test ($TARGET)
  env:
    TARGET: aarch64-apple-darwin
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-xcode
  setup_script:
    - curl --proto '=https' --tlsv1.2 -fsSL --retry 10 --retry-connrefused https://sh.rustup.rs | sh -s -- -y --profile minimal --default-toolchain nightly --no-modify-path
  test_script:
    - . "$HOME/.cargo/env"
    - cargo test --all --all-features --exclude benchmarks -- --test-threads=1
    - cargo test --all --all-features --exclude benchmarks --release -- --test-threads=1
