[tool.poetry]
name = "benchmarks"
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.8"
matplotlib = "3.6"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
