name: Release

permissions: {}

on:
  push:
    tags:
      - crossbeam-[0-9]+.*
      - crossbeam-[a-z]+-[0-9]+.*

defaults:
  run:
    shell: bash --noprofile --norc -CeEuxo pipefail {0}

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  create-release:
    if: github.repository_owner == 'crossbeam-rs'
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: write # for taiki-e/create-gh-release-action
    steps:
      - uses: taiki-e/checkout-action@7d1e50e93dc4fb3bba58f85018fadf77898aee8b # v1.4.2
      - uses: taiki-e/create-gh-release-action@eba8ea96c86cca8a37f1b56e94b4d13301fba651 # v1.11.0
        with:
          prefix: crossbeam(-[a-z]+)?
          changelog: $prefix/CHANGELOG.md
          title: $prefix $version
          branch: v0.8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: "!startsWith(github.ref_name, 'crossbeam-0')"
      # Since the crossbeam crate is located at the root, we need to handle it differently.
      # TODO: Consider moving crossbeam crate to a subdirectory.
      - uses: taiki-e/create-gh-release-action@eba8ea96c86cca8a37f1b56e94b4d13301fba651 # v1.11.0
        with:
          prefix: crossbeam(-[a-z]+)?
          changelog: CHANGELOG.md
          title: crossbeam $version
          branch: v0.8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: startsWith(github.ref_name, 'crossbeam-0')
